### ISSUE TITLE
Integration not able to load

### ISSUE THREAD

**Issue by holgeradam** [nicolasberthel/hass-becker-component#10]
Hey there,

I'm trying to get my Becker compatible covers into Home Assistant and I stumbled upon your pybecker repo and this one.
So far I've been able to install pybecker and pair and control the covers on the command line. However I'm not able to use this HA integration to have the covers as entities. I suspect it's got something to do with the setup/version of HA and how I installed pybecker. I'm a bit lost here in where to look and what I got wrong during the installation, so I appreciate any hint in the right direction. Thanks in advance
Here are the details:

- Home Assistant core-2021.7.3 and supervisor-2021.06.8 running on Home Assistant OS 6.1
- HW is a Raspberry Pi 3b and a Becker Centronic Stick V2
- pybecker installed via pip in ssh session on supervisor, located in /usr/lib/python3.9/site-packages
- pybecker cannot be called directly, instead I have to use python3 and the path to site-packages in the console
- covers paired and working in ssh session by calling for example: python3 /usr/lib/python3.9/site-packages/pybecker -a DOWN -c 1 
- hass-becker-component cloned to sub directory of custom_components
- ha core logs shows several errors during start up:

2021-07-20 20:22:04 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration becker which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-07-20 20:23:08 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing becker/recorder.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.hass-becker-component.recorder'
2021-07-20 20:23:08 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing becker/logbook.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.hass-becker-component.logbook'
2021-07-20 20:23:08 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing becker/system_health.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.hass-becker-component.system_health'
2021-07-20 20:23:08 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing becker/group.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 33, in _process
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.hass-becker-component.group'

**Comment by holgeradam** [comment]
Okay, I got a little further. I was able to run pybecker using `python3 -m pybecker -h` using the m flag to run a module as a script. That way it was possible to use the command_line platform for a custom cover entity.

**Comment by gschmidl** [comment]
Rename the "hass-becker-component" directory to "becker" in config/custom_components, delete the "`__pycache__`" directory in there, check configuration, restart HA, and it should work!

**Comment by holgeradam** [comment]
That was it, thank you!
