### ISSUE TITLE
Value Template for becker cover not working

### ISSUE THREAD

**Issue by RainerStaude** [nicolasberthel/hass-becker-component#11]
I'm playing around with value template for becker cover. Therefore I added the following to configuration.yaml:

```yaml
cover:
  - platform: becker
    device: "/dev/centronicusb"
    covers:
      rollo_test_2:
        friendly_name: "Rollo Test 2"
        channel: "3:5"         
        value_template: "{{states('sun.sun') == 'below_horizon'}}"
```

Unfortunately I got the following error:

```
2022-01-05 21:59:20 ERROR (MainThread) [homeassistant.components.cover] Error while setting up becker platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/becker/cover.py", line 113, in async_setup_platform
    entity_ids = extract_entities(device, "cover", None, templates)
  File "/config/custom_components/becker/__init__.py", line 37, in extract_entities
    template_entity_ids = template.extract_entities()
AttributeError: 'Template' object has no attribute 'extract_entities'

```

Is anybody using working templates with becker covers?

I'm currently adding support to listen to wall mount or handheld becker transmitter. This allows to track the position of the covers in HA even when operated by the becker transmitter.
When testing my changes together with templates I found this issue (which is also there in unchanged implementation).

**Comment by RainerStaude** [comment]
Closed with my latest update:
https://github.com/RainerStaude/hass-becker-component-plus-pybecker
