### ISSUE TITLE
Error "'TravelCalculator' object has no attribute '_calculate_travel_time'"

### ISSUE THREAD

**Issue by josecarre** [nicolasberthel/hass-becker-component#15]
Hi, since I have updated HA to 2023.5.0 I'm getting this error. Before it has been working for months without any issues with any HA version... i will debug it a bit more, but meanwhile I open an issue here so that we can track it.

Full error in log:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/becker/cover.py:392
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:55:27 AM (4 occurrences)
Last logged: 10:20:56 AM

[546827776640] 'TravelCalculator' object has no attribute '_calculate_travel_time'
[546834194080] 'TravelCalculator' object has no attribute '_calculate_travel_time'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 981, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/becker/cover.py", line 358, in async_close_cover
    self._travel_to_position(CLOSED_POSITION)
  File "/config/custom_components/becker/cover.py", line 392, in _travel_to_position
    travel_time = self._tc._calculate_travel_time(
AttributeError: 'TravelCalculator' object has no attribute '_calculate_travel_time'

```

**Comment by josecarre** [comment]
Maybe some changes are required in `cover.py`? This is the section affected following the logs:
```
    def _travel_to_position(self, position):
        """Start TravelCalculator and update ha-state."""
        # In TravelCalculator 0 is open, 100 is closed.
        travel_time = self._tc._calculate_travel_time(
            self.current_cover_position - position
        )
        if self._template is None:
            _LOGGER.debug(
                "%s is travelling from position %s to %s in %s seconds",
                self.name, self.current_cover_position, position, travel_time,
            )
            self._tc.start_travel(100 - position)
            self._update_scheduled_ha_state_callback(travel_time)
        return travel_time
```

**Comment by josecarre** [comment]
And some hours later... something arrived :)

![image](https://user-images.githubusercontent.com/10371413/236190014-147d5e04-f1fc-4ac9-8352-7a020d77b3d9.png)

I've tested it and works like a charm, thanks! We can close this issue.

**Comment by RainerStaude** [comment]
Just to note that this is for [this](https://github.com/RainerStaude/hass-becker-component-plus-pybecker) integration, which is an improved version of Nicolas integration [here](https://github.com/nicolasberthel/hass-becker-component).
